version: '3'

services:
    admin:
        build:
            context: .
            args:
                - APP_NAME=admin
        environment:
            - APP_NAME=admin
        ports:
            - "3003:3003"
        env_file:
            - .env
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:3003" ]
            interval: 10s
            retries: 5

    # user:
    #     build:
    #         context: .
    #         args:
    #             - APP_NAME=user
    #     environment:
    #         - APP_NAME=user
    #     env_file:
    #         - .env
    #     ports:
    #         - "3002:3002"
    #     healthcheck:
    #         test: [ "CMD", "curl", "-f", "http://localhost:3002" ]
    #         interval: 10s
    #         retries: 5

    # batch:
    #     build:
    #         context: .
    #         args:
    #             - APP_NAME=batch
    #     environment:
    #         - APP_NAME=batch
    #     env_file:
    #         - .env
    #     ports:
    #         - "3006:3006"
    #     healthcheck:
    #         test: [ "CMD", "curl", "-f", "http://localhost:3006" ]
    #         interval: 10s
    #         retries: 5

    # socket:
    #     build:
    #         context: .
    #     environment:
    #         - APP_NAME=socket
    #     args:
    #         - APP_NAME=socket
    #     env_file:
    #         - .env
    #     ports:
    #         - "3004:3004"
    #     healthcheck:
    #         test: [ "CMD", "curl", "-f", "http://localhost:3004" ]
    #         interval: 10s
    #         retries: 5

    # vps:
    #     build:
    #         context: .
    #     environment:
    #         - APP_NAME=vps
    #     args:
    #         - APP_NAME=vps
    #     env_file:
    #         - .env
    #     ports:
    #         - "3005:3005"
    #     healthcheck:
    #         test: [ "CMD", "curl", "-f", "http://localhost:3005" ]
    #         interval: 10s
    #         retries: 5

